<?php

/*
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Apigee\Edge\Tests\Test\EntitySerializer\PropertyValidator;

use Apigee\Edge\Entity\EntityInterface;
use Exception;
use stdClass;

/**
 * Extra validation for serialized and deserialized values of complex
 * properties.
 */
interface PropertyValidatorInterface
{
    /**
     * Validates a property.
     *
     * @param stdClass $input
     *   JSON decoded value of the input from Apigee Edge.
     * @param stdClass $output
     *   JSON decoded value of the API request body generated by a serializer.
     * @param EntityInterface $entity
     *   The original entity object - the source of the generated output.
     *
     * @throws Exception
     *   When the validation fails.
     */
    public function validate(stdClass $input, stdClass $output, EntityInterface $entity): void;

    /**
     * The name of the validated property in the input and output.
     *
     * @return string
     */
    public static function validatedProperty(): string;
}
