<?php

/*
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Apigee\Edge\Tests\Test\EntitySerializer\PropertyValidator;

/**
 * For those properties that are _knowingly_ represented differently in the
 * input than in the input generated by the serializer.
 *
 * These properties gets removed before the entity serializer compares
 * (the remaining) properties in the end.
 *
 * In case of the Management API this is the case for createdAt and modifiedAt
 * properties, because we do not store the milliseconds for these dates.
 *
 * In case on Monetization this is the case for all nested entity reference
 * properties. The input contains the complete (sometimes incomplete) nested
 * entity object, but in the API request payloads we only need to send the
 * id of the nested entity.
 */
interface RemoveIfPropertyValidPropertyValidatorInterface extends PropertyValidatorInterface
{
}
